version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "9000:9000"
    volumes:
      - ./server:/app/server
    command: python main.py


  react-app:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start